### ISSUE TITLE
https://urs.earthdata.nasa.gov/ log in does not work

### ISSUE THREAD

**Issue by goriliukasbuxton** [ASFHyP3/hyp3-sdk#171]
My log in works with https://urs.earthdata.nasa.gov/, but does not work with HyP3

**Comment by jhkennedy** [comment]
Hi @goriliukasbuxton, this is likely due to the problems encountered in #170

To acces ASF data, you need to accept the ASF EULA and specify a "Study Area" in your Earthdata Login user profile. 

If you go to https://search.asf.alaska.edu/ and login, it should prompt you to do so. 

You can verify you've got everything you need by downloading this XML file: https://datapool.asf.alaska.edu/METADATA_SLC/SA/S1A_IW_SLC__1SDV_20220703T154846_20220703T154912_043938_053EBC_D45D.iso.xml

**Comment by jhkennedy** [comment]
@goriliukasbuxton I'm going to close this issue in lieu of #170 -- let me know if you're still having problems accessing HyP3!
