### ISSUE TITLE
submit_insar_isce_burst_job() Error

### ISSUE THREAD

**Issue by amirafshari** [ASFHyP3/hyp3-sdk#268]
Hi everyone,
I'm trying to request ISCE InSAR in Google Colab with **submit_insar_isce_burst_job()** fucntion, but, this error arises:

![Screenshot from 2024-03-11 19-25-58](https://github.com/ASFHyP3/hyp3-sdk/assets/17769927/9d58237f-f3c6-4468-917c-842968fa21dd)

Everything works fine with **submit_insar_job()** function with the same environment and set of parameters.

**To Reproduce**
```
granules = [
    'S1A_IW_SLC__1SDV_20230129T033452_20230129T033519_046993_05A2FE_BE0B',
    'S1A_IW_SLC__1SDV_20230210T033451_20230210T033518_047168_05A8CD_E5B0',
]
```
```
insar_isce = hyp3.submit_insar_isce_burst_job(granule1=granules[0], granule2=granules[1])
```

**Additional context**
Good to know that the **prepare_insar_isce_burst_job()** works fine, too.

![Screenshot from 2024-03-11 19-32-33](https://github.com/ASFHyP3/hyp3-sdk/assets/17769927/797127c5-c7a3-49b1-a6e1-83d3e1cb8493)

**Comment by forrestfwilliams** [comment]
Hey @amirafshari when using `submit_burst_insar_job`, you'll need to use **Burst granule** names instead of SLC granule names. You can find **Burst granules** using a [S1 Burst search](https://search.asf.alaska.edu/#/?maxResults=250&polygon=POLYGON((36.1104%2036.5194,36.2733%2036.5194,36.2733%2036.5848,36.1104%2036.5848,36.1104%2036.5194))&searchType=Geographic%20Search&searchList=S1A_IW_SLC__1SDV_20230129T033452_20230129T033519_046993_05A2FE_BE0B&resultsLoaded=true&granule=S1_043817_IW3_20230210T033504_VV_E5B0-BURST&zoom=8.110&center=37.235,34.837&dataset=SENTINEL-1%20BURSTS&start=2023-01-26T06:00:00Z&end=2023-04-01T04:59:59Z&polarizations=VV) in Vertex, or via [asf_search](https://docs.asf.alaska.edu/asf_search/searching/).

For example:
```python
granules = [
    'S1_043817_IW3_20230129T033505_VV_BE0B-BURST',
    'S1_043817_IW3_20230210T033504_VV_E5B0-BURST',
]
insar_isce = hyp3.submit_insar_isce_burst_job(granule1=granules[0], granule2=granules[1])
```
